[package]
name = "diem-resource-viewer"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem resource viewer"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
# diem-workspace-hack = 
move-resource-viewer = { git = "https://github.com/simsekgokhan/move-0L-v6", branch = "v6-libra" }
diem-types = { path = "../../types"  }
move-core-types = { git = "https://github.com/simsekgokhan/move-0L-v6", branch = "v6-libra" }
move-binary-format = { git = "https://github.com/simsekgokhan/move-0L-v6", branch = "v6-libra" }

anyhow = "1.0.52"
