[package]
name = "transaction-builder-generator"
version = "0.1.0"
authors = ["Diem Association <opensource@diem.com>"]
description = "Diem transaction-builder"
repository = "https://github.com/diem/diem"
homepage = "https://diem.com"
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies]
anyhow = "1.0.52"
heck = "0.3.2"
regex = "1.4.3"
structopt = "0.3.21"
textwrap = "0.13.4"
serde_yaml = "0.8.17"

diem-types = { path = "../../types" }
diem-workspace-hack = { path = "../../crates/diem-workspace-hack" }
move-core-types = { git = "https://github.com/simsekgokhan/move-0L", rev = "f75ad3d67de41be8d4989fa398abbcbcfdb67806" }
serde-reflection = "0.3.5"
serde-generate = "0.20.6"
bcs = "0.1.2"

[dev-dependencies]
tempfile = "3.2.0"
which = "4.0.2"

[features]
default = []

[[bin]]
name = "generate-transaction-builders"
path = "src/generate.rs"
test = false
