[package]
name = "ol-genesis-tools"
version = "0.1.0"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.33"
futures = "0.3"
tokio = { version = "1.3.0", features = ["full"] }
bcs = "0.1.2"
diem-crypto = { path = "../../crates/diem-crypto" }
diem-types = { path = "../../types" }
backup-cli = { path = "../../storage/backup/backup-cli", version = "0.1.0" }
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.58"
backup-service = { path = "../../storage/backup/backup-service", version = "0.1.0" }
storage-interface = { path = "../../storage/storage-interface", version = "0.1.0" }
move-core-types = { git = "https://github.com/simsekgokhan/move-0L", rev = "f75ad3d67de41be8d4989fa398abbcbcfdb67806" }
vm-genesis={path="../../diem-move/vm-genesis", version="0.1.0"}
diem-wallet = { path = "../../crates/diem-wallet", version = "0.1.0"}
gumdrop = "0.8.0"
ol = { path = "../cli/"}
ol-keys = { path = "../keys/", version = "0.1.0" }
ol-types = { path = "../types/" }
language-e2e-tests = { path = "../../diem-move/e2e-tests", version="0.1.0"}
#diem-network-address = { path = "../../network/network-address", version = "0.1.0" }

[dev-dependencies]
tokio-test = "*"