[package]
name = "ol-genesis-tools"
version = "0.1.0"
authors = [""]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.33"
futures = "0.3"
tokio = { version = "1.3.0", features = ["full"] }
bcs = "0.1.2"
diem-crypto = { path = "../../crates/diem-crypto" }
diem-types = { path = "../../types" }
backup-cli = { path = "../../storage/backup/backup-cli", version = "0.1.0" }
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.58"
# backup-service = { path = "../../storage/backup/backup-service", version = "0.1.0" }
storage-interface = { path = "../../storage/storage-interface", version = "0.1.0" }
move-core-types = { git = "https://github.com/simsekgokhan/move-0L-v6", branch = "v6-libra" }
vm-genesis={path="../../diem-move/vm-genesis", version="0.1.0"}
diem-wallet = { path = "../../crates/diem-wallet", version = "0.1.0"}
gumdrop = "0.8.0"
ol = { path = "../cli/"}
ol-keys = { path = "../keys/", version = "0.1.0" }
ol-types = { path = "../types/" }
language-e2e-tests = { path = "../../diem-move/e2e-tests", version="0.1.0"}
#diem-network-address = { path = "../../network/network-address", version = "0.1.0" }
diem-logger = { path = "../../crates/diem-logger" }
diem-state-view = { path = "../../storage/state-view" }

#for testing only
diem-json-rpc = { path = "../../json-rpc" }
reqwest = { version = "0.11.2", features = ["blocking", "json"], default_features = false }
# genersis blob reading
diem-genesis-tool = { path = "../../config/management/genesis", version = "0.1.0" }
diem-temppath = { path = "../../crates/diem-temppath", version = "0.1.0" }
move-binary-format = { git = "https://github.com/simsekgokhan/move-0L-v6", branch = "v6-libra" }
move-vm-runtime = { git = "https://github.com/simsekgokhan/move-0L-v6", branch = "v6-libra" }
move-bytecode-utils = { git = "https://github.com/simsekgokhan/move-0L-v6", branch = "v6-libra" }
move-vm-types = { git = "https://github.com/simsekgokhan/move-0L-v6", branch = "v6-libra" }
diem-config = { path = "../../config" }
diem-secure-storage = { path = "../../secure/storage/", version = "0.1.0" }
diem-vm = { path = "../../diem-move/diem-vm", version = "0.1.0" }
diem-framework-releases = { path = "../../diem-move/diem-framework/DPN/releases" }

ol-smoke-tests = { path = "../smoke-tests/"}

[dev-dependencies]
tokio-test = "*"
rand = "0.8.3"

