[package]
name = "ol-types"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
bcs = "0.1.2"
diem-config = { path = "../../config/", version = "0.1.0" }
reqwest = { version = "0.11.2", features = ["blocking", "json"], default_features = false }
diem-types = { path = "../../types/" }
serde = { version = "1", features = ["serde_derive"] }
serde_json = "1"
hex = { version = "0.4.2", features = ["serde"] }
byteorder = "1"
diem-global-constants = { path = "../../config/global-constants", version = "0.1.0"}
dirs = "2.0.2"
machine-ip = "0.2.1"
rustyline = "6.2.0"
ajson = "0.2.3"
diem-crypto = { path = "../../crypto/crypto/" }
diem-genesis-tool = {path = "../../config/management/genesis", version = "0.1.0", features = ["testing"] }
toml = "0.5.6"
anyhow = "1.0.33"
url = { version = "^2.1", features = ["serde"]}
dialoguer = "0.8.0"
once_cell = "1.7.2"
ol-keys = { path = "../keys" }
move-core-types = { path = "../../language/move-core/types" }
sha2 = "0.9.1"
num-format = "0.4.0"

[dev-dependencies]
ol-fixtures = { path = "../../ol/fixtures" }